// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTp_DlZTLPtScvzedEvh5b21eR12_P1PE',
    appId: '1:369862962931:web:89c65fe1a90b2e83351186',
    messagingSenderId: '369862962931',
    projectId: 'catatan-f22ab',
    authDomain: 'catatan-f22ab.firebaseapp.com',
    storageBucket: 'catatan-f22ab.firebasestorage.app',
    measurementId: 'G-PDSS748R4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz_uX9m9bk1iBLmakujHkNxYILftoL-U0',
    appId: '1:369862962931:android:f8f4741aa721add3351186',
    messagingSenderId: '369862962931',
    projectId: 'catatan-f22ab',
    storageBucket: 'catatan-f22ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7bwTnqKwdJLz8wXE09cTUYKGQoGSjoqM',
    appId: '1:369862962931:ios:8b76ce01c93cbb5f351186',
    messagingSenderId: '369862962931',
    projectId: 'catatan-f22ab',
    storageBucket: 'catatan-f22ab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7bwTnqKwdJLz8wXE09cTUYKGQoGSjoqM',
    appId: '1:369862962931:ios:8b76ce01c93cbb5f351186',
    messagingSenderId: '369862962931',
    projectId: 'catatan-f22ab',
    storageBucket: 'catatan-f22ab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTp_DlZTLPtScvzedEvh5b21eR12_P1PE',
    appId: '1:369862962931:web:ea7294bae7734848351186',
    messagingSenderId: '369862962931',
    projectId: 'catatan-f22ab',
    authDomain: 'catatan-f22ab.firebaseapp.com',
    storageBucket: 'catatan-f22ab.firebasestorage.app',
    measurementId: 'G-KXJN13J68T',
  );

}